import 'dart:isolate';
import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;
import 'package:pawsitive_sync/data/care_repository.dart';
import 'package:pawsitive_sync/domain/models.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

/// Raw TTF bytes for the PDF. Plain bytes so they can be sent to a
/// background isolate. Noto Sans (+ Arabic fallback) because the app’s Geist
/// files are CFF OpenType, which the pdf package cannot embed.
class VetReportFonts {
  const VetReportFonts({required this.latin, required this.arabic});

  final Uint8List latin;
  final Uint8List arabic;

  static VetReportFonts? _cache;

  static Future<VetReportFonts> load() async {
    final cached = _cache;
    if (cached != null) return cached;
    Future<Uint8List> bytes(String name) async =>
        (await rootBundle.load('assets/fonts/pdf/$name.ttf')).buffer
            .asUint8List();
    final (latin, arabic) = await (
      bytes('NotoSans-Regular'),
      bytes('NotoSansArabic-Regular'),
    ).wait;
    return _cache = VetReportFonts(latin: latin, arabic: arabic);
  }
}

/// The built file plus its page count (for the `report.pdf_built` log).
typedef VetReportPdf = ({Uint8List bytes, int pages});

/// Builds the PDF on a background isolate so layout never janks the UI.
Future<VetReportPdf> buildVetReportPdfInBackground({
  required Pet pet,
  required PetReport report,
  required bool showCaregivers,
  required DateTime generatedAt,
}) async {
  final fonts = await VetReportFonts.load();
  return Isolate.run(
    () => buildVetReportPdf(
      pet: pet,
      report: report,
      showCaregivers: showCaregivers,
      generatedAt: generatedAt,
      fonts: fonts,
    ),
  );
}

/// `<Pet>-care-report-<yyyy-mm-dd>.pdf`, safe for any file system.
String vetReportFileName(Pet pet, DateTime day) {
  final safe = pet.name
      .trim()
      .replaceAll(RegExp(r'[\\/:*?"<>|\s]+'), '-')
      .replaceAll(RegExp(r'-+'), '-');
  return '${safe.isEmpty ? 'Pet' : safe}-care-report-${dayKey(day)}.pdf';
}

const _months = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec',
];

String _date(DateTime d) => '${_months[d.month - 1]} ${d.day}, ${d.year}';

String _dayKeyLabel(String key) {
  final d = DateTime.tryParse(key);
  return d == null ? key : '${_months[d.month - 1]} ${d.day}';
}

String _outcome(LogOutcome outcome) => switch (outcome) {
  LogOutcome.given => 'Given',
  LogOutcome.skipped => 'Skipped',
  LogOutcome.uncertain => 'Not sure',
};

/// Vet-ready PDF: header, one table row per medicine, missed doses, notes,
/// optional caregiver log, and an honest footer.
Future<VetReportPdf> buildVetReportPdf({
  required Pet pet,
  required PetReport report,
  required bool showCaregivers,
  required DateTime generatedAt,
  required VetReportFonts fonts,
}) async {
  final regular = pw.Font.ttf(ByteData.sublistView(fonts.latin));
  final arabic = pw.Font.ttf(ByteData.sublistView(fonts.arabic));
  // One weight keeps the bundle small; headings stand out by size.
  final medium = regular;
  final bold = regular;
  final theme = pw.ThemeData.withFont(
    base: regular,
    bold: bold,
    fontFallback: [arabic],
  );
  const ink = PdfColor.fromInt(0xFF2C3531);
  const muted = PdfColor.fromInt(0xFF6B726E);
  const brand = PdfColor.fromInt(0xFF4A7C59);
  const hairline = PdfColor.fromInt(0xFFE4E5E1);

  pw.Widget heading(String text) => pw.Padding(
    padding: const pw.EdgeInsets.only(top: 18, bottom: 6),
    child: pw.Text(
      text,
      style: pw.TextStyle(font: bold, fontSize: 13, color: ink),
    ),
  );

  final profile = [
    pet.speciesLabel,
    if (pet.ageYears > 0) '${pet.ageYears} yrs',
    if (pet.weightKg > 0) '${pet.weightKg} kg',
  ].join(' · ');

  final doc = pw.Document(
    theme: theme,
    title: '${pet.name} care report',
    creator: 'Pawsitive',
  );
  var pages = 0;
  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.letter,
      margin: const pw.EdgeInsets.fromLTRB(48, 44, 48, 44),
      footer: (context) {
        pages = context.pagesCount;
        return pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Divider(color: hairline),
            pw.Row(
              children: [
                pw.Expanded(
                  child: pw.Text(
                    'Generated by Pawsitive on ${_date(generatedAt)} — '
                    'owner-reported, not a medical record.',
                    style: const pw.TextStyle(fontSize: 8, color: muted),
                  ),
                ),
                pw.Text(
                  'Page ${context.pageNumber} of ${context.pagesCount}',
                  style: const pw.TextStyle(fontSize: 8, color: muted),
                ),
              ],
            ),
          ],
        );
      },
      build: (context) => [
        pw.Text(
          pet.name,
          style: pw.TextStyle(font: bold, fontSize: 22, color: ink),
        ),
        pw.SizedBox(height: 2),
        pw.Text(
          'Care report · ${_date(report.from)} – ${_date(report.to)}',
          style: const pw.TextStyle(fontSize: 11, color: brand),
        ),
        pw.SizedBox(height: 6),
        pw.Text(profile, style: const pw.TextStyle(fontSize: 10, color: ink)),
        if (pet.conditions.isNotEmpty)
          pw.Text(
            'Conditions: ${pet.conditions.join(', ')}',
            style: const pw.TextStyle(fontSize: 10, color: ink),
          ),
        pw.SizedBox(height: 10),
        pw.Text(
          'Given ${report.given} · Skipped ${report.skipped} · '
          'Not sure ${report.uncertain} · Missed ${report.missed}',
          style: pw.TextStyle(font: medium, fontSize: 10, color: ink),
        ),
        heading('Medicines'),
        pw.TableHelper.fromTextArray(
          headers: [
            'Medicine',
            'Dose',
            'Schedule',
            'Given',
            'Expected',
            'Skipped',
            'Not sure',
            'Missed',
          ],
          data: [
            for (final line in report.lines)
              [
                // "Antibiotic (stopped Oct 2)" for a stopped medicine.
                line.medication.historyName,
                line.medication.doseLabel,
                line.medication.whenLabel.isEmpty
                    ? '—'
                    : line.medication.whenLabel,
                '${line.given}',
                '${line.expected}',
                '${line.skipped}',
                '${line.uncertain}',
                '${line.missed}',
              ],
          ],
          headerStyle: pw.TextStyle(font: bold, fontSize: 9, color: ink),
          cellStyle: const pw.TextStyle(fontSize: 9, color: ink),
          headerDecoration: const pw.BoxDecoration(
            color: PdfColor.fromInt(0xFFE9F1EB),
          ),
          border: const pw.TableBorder(
            horizontalInside: pw.BorderSide(color: hairline, width: 0.5),
            bottom: pw.BorderSide(color: hairline, width: 0.5),
          ),
          cellAlignments: {
            for (var i = 3; i < 8; i++) i: pw.Alignment.centerRight,
          },
          cellPadding: const pw.EdgeInsets.symmetric(
            horizontal: 4,
            vertical: 5,
          ),
        ),
        heading('Missed doses'),
        if (report.missedDoses.isEmpty)
          pw.Text(
            'None — every scheduled dose has a log.',
            style: const pw.TextStyle(fontSize: 10, color: muted),
          )
        else ...[
          for (final miss in report.missedDoses)
            pw.Bullet(
              text: missedDoseLabel(miss),
              style: const pw.TextStyle(fontSize: 9, color: ink),
            ),
          if (report.missedDoses.length >= PetReport.maxMissedListed)
            pw.Text(
              'Showing the ${PetReport.maxMissedListed} most recent.',
              style: const pw.TextStyle(fontSize: 8, color: muted),
            ),
        ],
        heading('Symptom notes'),
        if (report.notes.isEmpty)
          pw.Text(
            'No symptom notes in this period.',
            style: const pw.TextStyle(fontSize: 10, color: muted),
          )
        else
          for (final entry in report.notes.entries)
            pw.Bullet(
              text: '${entry.key} ×${entry.value}',
              style: const pw.TextStyle(fontSize: 9, color: ink),
            ),
        if (showCaregivers && report.recent.isNotEmpty) ...[
          heading('Dose log'),
          pw.TableHelper.fromTextArray(
            headers: ['Day', 'Time', 'Medicine', 'Outcome', 'Logged by'],
            data: [
              for (final entry in report.recent)
                [
                  _dayKeyLabel(entry.day),
                  entry.timeLabel,
                  entry.medicationName,
                  _outcome(entry.outcome),
                  entry.who,
                ],
            ],
            headerStyle: pw.TextStyle(font: bold, fontSize: 9, color: ink),
            cellStyle: const pw.TextStyle(fontSize: 9, color: ink),
            border: const pw.TableBorder(
              horizontalInside: pw.BorderSide(color: hairline, width: 0.5),
            ),
            cellPadding: const pw.EdgeInsets.symmetric(
              horizontal: 4,
              vertical: 4,
            ),
          ),
        ],
      ],
    ),
  );
  final bytes = await doc.save();
  return (bytes: bytes, pages: pages);
}

/// "Oct 4 · Insulin (morning 7:00 AM)" — one missed dose in the report,
/// with its scheduled (custom or default) time.
String missedDoseLabel(MissedDose miss) {
  final time = miss.timeLabel.isEmpty ? miss.part.timeLabel : miss.timeLabel;
  return '${_months[miss.day.month - 1]} ${miss.day.day} · '
      '${miss.medicationName} (${miss.part.label.toLowerCase()} $time)';
}
